{% set name = "winrt-windows.storage.streams" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/winrt_windows_storage_streams-{{ version }}.tar.gz
  sha256: d0e68b0ae9bb53b2d423332771a4679f5862ddc01fe57dfef89fe25b982dd6d1

build:
  skip: true  # [py>=313]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.9,<3.13
    - setuptools
    - winrt-sdk
    - pip
  run:
    - python >=3.9,<3.13
    - winrt-runtime ==2.1.0

test:
  imports:
    - winrt_windows.storage.streams
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python projection of Windows Runtime (WinRT) APIs
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
