{% set name = "winrt-windows.devices.bluetooth.advertisement" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/winrt_windows_devices_bluetooth_advertisement-{{ version }}.tar.gz
  sha256: d0eff0e0830b806b1351a78a397575c72e1ffa3a1cd9a1df3ef961094be61d36

build:
  skip: true  # [py>=313]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.9,<3.13
    - setuptools
    - winrt-sdk
    - pip
  run:
    - python >=3.9,<3.13
    - winrt-runtime ==2.1.0

test:
  imports:
    - winrt_windows.devices.bluetooth.advertisement
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python projection of Windows Runtime (WinRT) APIs
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
