{% set name = "winrt-windows.foundation" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/winrt_windows_foundation-{{ version }}.tar.gz
  sha256: 6d57f35a5d744c3bc1a897c9b539322887a87765bebce47fddcfb942de587d5a

build:
  skip: true  # [py>=313]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.9,<3.13
    - setuptools
    - winrt-sdk
    - pip
  run:
    - python >=3.9,<3.13
    - winrt-runtime ==2.1.0

test:
  imports:
    - winrt_windows.foundation
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python projection of Windows Runtime (WinRT) APIs
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
